#!/usr/bin/env python
import csv
import sys

for entry in csv.reader(sys.stdin.readlines()):
    print "zone \"%s\" {" % entry[0]
    print "\ttype slave;"
    print "\tfile \"/var/cache/bind/db.%s\";" % entry[0]
    print "\tmasters { %s; };" % entry[1]
    print "};"
